[package]
name = "metrics-util"
version = "0.4.0"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
edition = "2018"

license = "MIT"

description = "Helper types/functions used by the metrics ecosystem."
homepage = "https://github.com/metrics-rs/metrics"
repository = "https://github.com/metrics-rs/metrics"
documentation = "https://docs.rs/metrics-util"
readme = "README.md"

categories = ["development-tools::debugging"]
keywords = ["metrics", "quantile", "percentile"]

[[bench]]
name = "bucket"
harness = false

[[bench]]
name = "registry"
harness = false

[[bench]]
name = "streaming_integers"
harness = false

[dependencies]
metrics = { version = "^0.13", path = "../metrics", features = ["std"] }
crossbeam-epoch = "^0.8"
crossbeam-utils = "^0.7"
serde = "^1.0"
arc-swap = "^0.4"
im = "^14"
parking_lot = "^0.10"

[dev-dependencies]
criterion = "^0.3"
lazy_static = "^1.3"
rand = { version = "^0.7", features = ["small_rng"] }
rand_distr = "^0.2"
