[package]
name = "metrics-util"
version = "0.3.1"
authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
edition = "2018"

license = "MIT"

description = "Helper types/functions used by the metrics ecosystem."
homepage = "https://github.com/metrics-rs/metrics"
repository = "https://github.com/metrics-rs/metrics"
documentation = "https://docs.rs/metrics-util"
readme = "README.md"

categories = ["development-tools::debugging"]
keywords = ["metrics", "quantile", "percentile"]

[[bench]]
name = "bucket"
harness = false

[[bench]]
name = "registry"
harness = false

[[bench]]
name = "streaming_integers"
harness = false

[dependencies]
metrics = { path = "../metrics", version = "^0.12" }
crossbeam-epoch = "^0.8"
serde = "^1.0"
arc-swap = "^0.4"
im = "^14"
sharded-slab = "0.0.9"
parking_lot = "^0.10"

[dev-dependencies]
crossbeam-utils = "^0.7"
criterion = "^0.2.9"
lazy_static = "^1.3"
rand = "^0.6"
